# Generated by Django 5.0.2 on 2024-12-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yulia_app_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
