# Generated by Django 5.0.2 on 2024-12-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yulia_app_1', '0002_coffee_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
