# Generated by Django 5.0.2 on 2024-12-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yulia_app_1', '0003_alter_coffee_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
