# Generated by Django 5.0.2 on 2024-12-11 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yulia_app_1', '0005_category_coffee_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yulia_app_1.category'),
        ),
    ]
