# Generated by Django 5.0.2 on 2024-12-13 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yulia_app_1', '0006_alter_coffee_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='coffee',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='yulia_app_1.category'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='yulia_app_1.tagtable'),
        ),
    ]
