# Generated by Django 5.0.2 on 2024-12-14 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yulia_app_1', '0007_tagtable_alter_coffee_cat_coffee_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gost_product', models.CharField(max_length=50)),
                ('gost_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='coffee',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='yulia_app_1.category'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tagtable', to='yulia_app_1.tagtable'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='gost',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yulia_app_1.gost'),
        ),
    ]
