# Generated by Django 5.0.2 on 2024-12-14 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yulia_app_1', '0008_gost_alter_coffee_cat_alter_coffee_tag_coffee_gost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='gost',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gost', to='yulia_app_1.gost'),
        ),
    ]
