# Generated by Django 5.0.2 on 2025-05-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yulia_app_1', '0009_alter_coffee_gost'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads_model/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории меню', 'verbose_name_plural': 'Категории меню'},
        ),
        migrations.AlterModelOptions(
            name='coffee',
            options={'verbose_name': 'Продуктовые позиции для кофейни', 'verbose_name_plural': 'Продуктовые позиции для кофейни'},
        ),
        migrations.AlterModelOptions(
            name='tagtable',
            options={'verbose_name': 'Тэги', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterField(
            model_name='coffee',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
