# Generated by Django 5.0.2 on 2025-05-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yulia_app_1', '0011_coffee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/'),
        ),
    ]
