# Generated by Django 5.0.2 on 2025-05-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yulia_app_1', '0013_alter_coffee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
