# Generated by Django 5.2.2 on 2025-08-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yulia_app_1', '0014_alter_coffee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('passport_num', models.IntegerField(max_length=50, unique=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Реквизиты клиентов',
                'verbose_name_plural': 'Реквизиты клиентов',
            },
        ),
    ]
