# Generated by Django 5.2.2 on 2025-08-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yulia_app_1', '0015_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport_num',
            field=models.IntegerField(unique=True),
        ),
    ]
