# Generated by Django 5.2.2 on 2025-08-18 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yulia_app_1', '0016_alter_client_passport_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='agreement_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
