# Generated by Django 5.2.2 on 2025-08-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yulia_app_1', '0017_client_agreement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='agreement_num',
            field=models.CharField(default='123'),
            preserve_default=False,
        ),
    ]
