# Generated by Django 5.2.2 on 2025-08-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yulia_app_1', '0018_client_agreement_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
