# Generated by Django 5.2.2 on 2025-09-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yulia_app_1', '0019_client_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='loskutova.yulia@gmail.com', max_length=100),
        ),
    ]
