# Generated by Django 5.2.2 on 2025-09-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yulia_app_1', '0020_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
